# Generated by Django 4.0.6 on 2022-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='Unknown author', max_length=255),
            preserve_default=False,
        ),
    ]
